# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRESHOST', 'localhost') %>
  password: <%= ENV.fetch('POSTGRESPASS', 'postgres') %>
  username: <%= ENV.fetch('POSTGRESUSER', 'postgres') %>

development:
  <<: *default
  database: docker-jenkins_dev

  
test:
  <<: *default
  database: docker-jenkins_test

production:
  <<: *default
  database: docker-jenkins_production
  username: docker-jenkins
  password: <%= ENV['DOCKER-JENKINS_DATABASE_PASSWORD'] %>
